name: molpal

channels:
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=11.3
  - python=3.8
  - pytorch::pytorch >=1.10
  - rdkit
  - pip
  - pip:
    - configargparse
    - h5py
    - numpy
    - ray >= 1.11
    - ray[tune]
    - pytorch-lightning
    - scikit-learn
    - tensorflow
    - tensorflow-addons
    - tqdm
